package io.github.Sammers21.cm.picker

object Aliases {
    val DefaultAliases = listOf<HeroAlias>(
            listOf("аббадон", "абадон", "абба") to "abaddon",
            listOf("алхимик", "алхим", "алхимос", "alch") to "alchemist",
            listOf("аппарат", "апарат") to "ancient-apparition",
            listOf("магина", "антимаг", "ам", "am") to "anti-mage",
            listOf("арк", "ark") to "arc-warden",
            listOf("акс") to "axe",
            listOf("бейн", "бэйн") to "bane",
            listOf("бэт", "бэтрайдер", "bat") to "batrider",
            listOf("beast", "бист") to "beastmaster",
            listOf("сикер") to "bloodseeker",
            listOf("бх") to "bounty-hunter",
            listOf("брю") to "brewmaster",
            listOf("брист") to "bristleback",
            listOf("бруда") to "broodmother",
            listOf("кент") to "centaur-warrunner",
            listOf("цк", "ck") to "chaos-knight",
            listOf("чен") to "chen",
            listOf("клинкз") to "clinkz",
            listOf("клок") to "clockwerk",
            listOf("цм", "cm") to "crystal-maiden",
            listOf("дс", "ds") to "dark-seer",
            listOf("вилка", "willow") to "dark-willow",
            listOf("даззл", "дазл") to "dazzle",
            listOf("дп", "dp") to "death-prophet",
            listOf("дис", "dis") to "disruptor",
            listOf("дум") to "doom",
            listOf("дк", "dk") to "dragon-knight",
            listOf("дровка", "тракса", "drwo") to "drow-ranger",
            listOf("земеля", "esp") to "earth-spirit",
            listOf("шейкер", "esh", "shaker") to "earthshaker",
            listOf("титан", "titan") to "elder-titan",
            listOf("эмбер", "имбирь") to "ember-spirit",
            listOf("инча", "енча", "ench") to "enchantress",
            listOf("энигма", "нигма") to "enigma",
            listOf("войд", "void") to "faceless-void",
            listOf("грим", "grim") to "grimstroke",
            listOf("гиро", "gyro", "guro") to "gyrocopter",
            listOf("хуск", "husk") to "huskar",
            listOf("инвокер", "вокер") to "invoker",
            listOf("висп") to "io",
            listOf("джакиро") to "jakiro",
            listOf("джагер", "джага", "jugger") to "juggernaut",
            listOf("котл", "kotl") to "keeper-of-the-light",
            listOf("кунка") to "kunkka",
            listOf("лц", "легионка", "lc") to "legion-commander",
            listOf("леший", "лешрак") to "leshrac",
            listOf("лич") to "lich",
            listOf("гуля", "найкс", "наикс") to "lifestealer",
            listOf("лина") to "lina",
            listOf("лион") to "lion",
            listOf("друид", "ld", "лд") to "lone-druid",
            listOf("луна") to "luna",
            listOf("люкан", "волк") to "lycan",
            listOf("магнус", "магнатавр") to "magnus",
            listOf("марс") to "mars",
            listOf("дуза", "медуза", "dusa") to "medusa",
            listOf("мипо", "мипарь") to "meepo",
            listOf("мирана") to "mirana",
            listOf("мк", "макака", "mk") to "monkey-king",
            listOf("морф") to "morphling",
            listOf("нага") to "naga-siren",
            listOf("фурион", "фура") to "natures-prophet",
            listOf("некр") to "necrophos",
            listOf("нс", "ns") to "night-stalker",
            listOf("нюкс","nyx") to "nyx-assassin",
            listOf("огр", "ogre") to "ogre-magi",
            listOf("омник", "омни") to "omniknight",
            listOf("оракл") to "oracle",
            listOf("од", "деваурер", "od") to "outworld-devourer",
            listOf("панго", "пангольер", "pango") to "pangolier",
            listOf("па", "pa") to "phantom-assassin",
            listOf("пл", "pl") to "phantom-lancer",
            listOf("феникс", "феня") to "phoenix",
            listOf("пак") to "puck",
            listOf("пудж", "жирный") to "pudge",
            listOf("пугна") to "pugna",
            listOf("квопа", "qop") to "queen-of-pain",
            listOf("разор") to "razor",
            listOf("рики") to "riki",
            listOf("рубик") to "rubick",
            listOf("ск", "sk") to "sand-king",
            listOf("шд", "sd") to "shadow-demon",
            listOf("сф", "sf") to "shadow-fiend",
            listOf("шаман", "shaman") to "shadow-shaman",
            listOf("сало") to "silencer",
            listOf("петух", "sm") to "skywrath-mage",
            listOf("слардар") to "slardar",
            listOf("сларк") to "slark",
            listOf("снайпер") to "sniper",
            listOf("спектра") to "spectre",
            listOf("корова") to "spirit-breaker",
            listOf("шторм", "cc", "ss") to "storm-spirit",
            listOf("свен") to "sven",
            listOf("течис", "течка", "минёр") to "techies",
            listOf("ланая", "ta") to "templar-assassin",
            listOf("тб", "tb") to "terrorblade",
            listOf("тайд") to "tidehunter",
            listOf("тимбер") to "timbersaw",
            listOf("тинкер") to "tinker",
            listOf("тини") to "tiny",
            listOf("трент", "tp", "тп") to "treant-protector",
            listOf("троль", "tw", "тв") to "troll-warlord",
            listOf("туск") to "tusk",
            listOf("андер", "pit", "lord") to "underlord",
            listOf("зомби") to "undying",
            listOf("урса") to "ursa",
            listOf("венга", "vs") to "vengeful-spirit",
            listOf("веник", "веном", "вено") to "venomancer",
            listOf("вайпер") to "viper",
            listOf("визаж") to "visage",
            listOf("варлок") to "warlock",
            listOf("вивер") to "weaver",
            listOf("вр", "врка", "wr") to "windranger",
            listOf("виверна", "ww") to "winter-wyvern",
            listOf("вд", "wd") to "witch-doctor",
            listOf("вк", "wk") to "wraith-king",
            listOf("зевс") to "zeus"
    )
}