package io.github.Sammers21.cm.picker

object Aliases {
    val DefaultAliases = listOf<HeroAlias>(
            listOf("аббадон") to "abaddon",
            listOf("алхимик", "алхим") to "alchemist",
            listOf("аппарат") to "ancient-apparition",
            listOf("магина", "антимаг", "ам", "am") to "anti-mage",
            listOf("арк", "ark") to "arc-warden",
            listOf("акс") to "axe",
            listOf("бейн", "бэйн") to "bane",
            listOf("бэт", "бэтрайдер", "bat") to "batrider",
            listOf("beast", "бист") to "beastmaster",
            listOf("сикер") to "bloodseeker",
            listOf("бх") to "bounty-hunter",
            listOf("брю") to "brewmaster",
            listOf("брист") to "bristleback",
            listOf("бруда") to "broodmother",
            listOf("кент") to "centaur-warrunner",
            listOf("цк") to "chaos-knight",
            listOf("чен") to "chen",
            listOf("клинкз") to "clinkz",
            listOf("клок") to "clockwerk",
            listOf("цм") to "crystal-maiden",
            listOf("дс") to "dark-seer",
            listOf("вилка") to "dark-willow",
            listOf("даззл") to "dazzle",
            listOf("дп") to "death-prophet",
            listOf("дис") to "disruptor",
            listOf("дум") to "doom",
            listOf("дк") to "dragon-knight",
            listOf("дровка", "тракса") to "drow-ranger",
            listOf("земеля") to "earth-spirit",
            listOf("шейкер") to "earthshaker",
            listOf("титан") to "elder-titan",
            listOf("эмбер", "имбирь") to "ember-spirit",
            listOf("инча", "енча") to "enchantress",
            listOf("энигма") to "enigma",
            listOf("войд") to "faceless-void",
            listOf("грим") to "grimstroke",
            listOf("гиро") to "gyrocopter",
            listOf("хуск") to "huskar",
            listOf("инвокер") to "invoker",
            listOf("висп") to "io",
            listOf("джакиро") to "jakiro",
            listOf("джагер") to "juggernaut",
            listOf("котл") to "keeper-of-the-light",
            listOf("кунка") to "kunkka",
            listOf("лц", "легионка") to "legion-commander",
            listOf("леший", "лешрак") to "leshrac",
            listOf("лич") to "lich",
            listOf("гуля") to "lifestealer",
            listOf("лина") to "lina",
            listOf("лион") to "lion",
            listOf("друид") to "lone-druid",
            listOf("луна") to "luna",
            listOf("люкан", "волк") to "lycan",
            listOf("магнус") to "magnus",
            listOf("марс") to "mars",
            listOf("дуза", "медуза") to "medusa",
            listOf("мипо") to "meepo",
            listOf("мирана") to "mirana",
            listOf("мк", "макака") to "monkey-king",
            listOf("морф") to "morphling",
            listOf("нага") to "naga-siren",
            listOf("фурион", "фура") to "natures-prophet",
            listOf("некр") to "necrophos",
            listOf("нс") to "night-stalker",
            listOf("нюкс") to "nyx-assassin",
            listOf("огр") to "ogre-magi",
            listOf("омник") to "omniknight",
            listOf("оракл") to "oracle",
            listOf("од", "деваурер") to "outworld-devourer",
            listOf("панго", "пангольер") to "pangolier",
            listOf("па") to "phantom-assassin",
            listOf("пл") to "phantom-lancer",
            listOf("феникс", "феня") to "phoenix",
            listOf("пак") to "puck",
            listOf("пудж", "жирный") to "pudge",
            listOf("пугна") to "pugna",
            listOf("квопа") to "queen-of-pain",
            listOf("разор") to "razor",
            listOf("рики") to "riki",
            listOf("рубик") to "rubick",
            listOf("ск") to "sand-king",
            listOf("шд") to "shadow-demon",
            listOf("сф") to "shadow-fiend",
            listOf("шаман") to "shadow-shaman",
            listOf("сало") to "silencer",
            listOf("петух") to "skywrath-mage",
            listOf("слардар") to "slardar",
            listOf("сларк") to "slark",
            listOf("снайпер") to "sniper",
            listOf("спектра") to "spectre",
            listOf("корова") to "spirit-breaker",
            listOf("шторм") to "storm-spirit",
            listOf("свен") to "sven",
            listOf("течис", "течка", "минёр") to "techies",
            listOf("ланая", "ta") to "templar-assassin",
            listOf("тб", "tb") to "terrorblade",
            listOf("тайд") to "tidehunter",
            listOf("тимбер") to "timbersaw",
            listOf("тинкер") to "tinker",
            listOf("тини") to "tiny",
            listOf("трент") to "treant-protector",
            listOf("троль") to "troll-warlord",
            listOf("туск") to "tusk",
            listOf("андер") to "underlord",
            listOf("зомби") to "undying",
            listOf("урса") to "ursa",
            listOf("венга") to "vengeful-spirit",
            listOf("веник") to "venomancer",
            listOf("вайпер") to "viper",
            listOf("вихаж") to "visage",
            listOf("варлок") to "warlock",
            listOf("вивер") to "weaver",
            listOf("вр") to "windranger",
            listOf("виверна") to "winter-wyvern",
            listOf("вд") to "witch-doctor",
            listOf("вк") to "wraith-king",
            listOf("зевс") to "zeus"
    )
}